Financial contributors welcome.

DeadDogDown Game Studio resides in South Africa with limited access to fund raising avenues.

If you wish to sponsor or donate our future development, please contact us directly for SWIFT details.

We welcome your support.
